### ISSUE TITLE
Reserve some top level prefixes for custom non-ecs fields

### ISSUE THREAD

**Issue by vbohata** [elastic/ecs#101]
I would like to add some top level prefix for our fields to avoid collision with evolving ECS schema. I want something short. I want to use 2letter organizations abbreviations. Is it safe to use 2 letter top level field name? Or do you think there will be another 2letter fields other than "os"?

Probably there should be official list of top level fields (probably 2letters, 1 is too short, and 3 unnecessarily makes the whole field name too long) that are forbidden to use in ECS ... so allowed to use for custom prefixes.
... or make some official custom reserved non-ecs prefixes (also mentioned in #52).

**Comment by ruflin** [comment]
In general I would not expect many collisions if we don't use abbreviations. Assuming we would have `apache` fields in ECS, I would expect that your fields needed for `apache` would be similar. In your case it seems you want to add abbreviations for organisations which are unique to you and as usual with abbreviation, on can mean multiple things. 

I don't expect us to add many (any?) additional 2 letter abbreviations outside `os` but I don't think we are at the point yet to make a promise here.

Would about having a longer prefix for all your custom fields which would be unique to you like your company name?

I understand more and more why we need to provide such a convention to prevent future collisions of ECS users.

**Comment by MikePaquette** [comment]
@vbohata @ruflin Interesting question.  I wonder if instead of reserving top level prefixes for custom non-ECS fields, we could do the opposite and reserve the ones we think ECS may use in the future, and as long as a custom implementation steers clear of these, it will be collision free.  Would this work?

For example: 

- Custom user-supplied prefixes and fields may co-exist with ECS Core and ECS Extended fields in an ECS-compliant implementation.
- Custom field names must not collide with any ECS namespaces/objects/prefixes.
- Custom top-level prefixes must not collide with any ECS namespaces/objects/prefixes, nor any ECS field names, nor any of the following names:

`aerospike, amqp, apache, apache2, apm, auditd, auditd, beat, beats, cassandra, cef, ceph, cloud, common, container, couchbase, dns, docker, dropwizard, elasticsearch, envoyproxy, etcd, file, flow, geo, geoip, golang, graphite, haproxy, hash, host, http, icinga, icmp, iis, jolokia, kafka, kibana, kubernetes, kvm, log, logstash, measurements, memcache, memcached, mongodb, munin, mysql, nfs, nginx, organization, os, osquery, php_fpm, postgresql, process, prometheus, rabbitmq, raw, redis, socks5, swiftype, system, tcp, threat, thrift-rpc, tls, traefik, transaction event, url, user, user_agent, uwsgi, vsphere, vulnerability, windows, zookeeper`

**Comment by webmat** [comment]
Hey folks, very good question indeed, and one we have touched internally in various discussions.

I think that working to define a comprehensive list of top level names we want to reserve is not the right approach. It's a lot of work, and the next top level object we decide to define may not even be in there, when we actually get to it :-)

I do think it makes sense to list explicitly some of the top level fields we have been discussing to add soon and that aren't in master yet, like `threat`, `related` and so on. I would see this as just a temporary measure until it does make it to master, however.

To answer @vbohata's question directly, I agree we need to document one or a few ways how users of ECS can safely add fields or top level objects that have a low risk of conflicting with future developments in ECS. There are more than one aspect to this:

* In your specific case, I think you would be ok adding pretty much as many 2-letter top level objects. We have a goal of using full names, except when the common parlance is extremely weighted towards using an acronym (e.g. `os` and `pid`). Right now I can't think of any other 2-letter acronym that's likely to make it to ECS Core's top level. 
  * However I don't think it makes sense for our recommendation on how to work around ECS to be "use a 2-letter top level object". It's just your preference at this time :-)
* In general, our internal discussions have been that people should be able to extend ECS inside existing ECS objects by adding the fields they want right alongside ECS fields. E.g. `host.foo_bar`.
  * This carries a direct risk of future conflict, if the practice of tracking `foo_bar`s starts spreading and we decide to include it in ECS and we pick a different datatype (e.g. `keyword` instead of `long`).
* Same goes with new top level objects. We're trying to define a common schema (especially ECS Core) that's relatively independent from concrete technologies. So creating a custom top level field to track details about a technology of choice is safe enough, until the point (if that comes) that it becomes a de-facto standard in the industry. At this point it may still not be part of ECS Core, but it may get into ECS Extended or another "less official / more experimental" level of ECS.

I still think it would be useful to suggest a 100% safe way that ECS users can avoid clashes with future ECS developments. Then the choice of using this safe way or not is left to the user, but at least the safe way is agreed upon.

To this effect, we could for example suggest the use of `custom` and/or `cust` or `c` \* as the safe top level where you can put everything you want. Also, if users wants to expand other existing ECS objects in a 100% safe way, they could use the same strategy inside each object: `host.custom.foo_bar`, `host.cust.foo_bar` or `host.c.foo_bar` (depending on their preference).

\* I think it's fine if schema customizations don't follow our goal of using full names. Whatever's in `cust` or `c` would by definition not be part of ECS anyway :-)

A quick note that I have mentioned "ECS Core" and "ECS Extended" in my answer. This is a concept we've been discussing internally and hasn't yet made it to the repo yet. But in short, it's a way to identify the set of fields that are most well defined and least likely to change (Core) vs fields that may be more tech-specific, more experimental or less well understood (Extended). Fields defined in Extended could eventually make it to Core if they become canonical and well defined enough, or they could remain in Extended.

**Comment by MikePaquette** [comment]
@webmat I like your approach better than counting on only a reserved list!

Also, "ECS Core" and "ECS Extended" are discussed in #93

**Comment by vbohata** [comment]
> In your specific case, I think you would be ok adding pretty much as many 2-letter top level objects. We have a goal of using full names, except when the common parlance is extremely weighted towards using an acronym (e.g. os and pid). Right now I can't think of any other 2-letter acronym that's likely to make it to ECS Core's top level.
    However I don't think it makes sense for our recommendation on how to work around ECS to be "use a 2-letter top level object". It's just your preference at this time :-)

I finally put all fields under our organization prefix. I decided to use our frequently used 4letter prefix. All fields inside this prefix copies the current and future (+ maybe future) ECS schema. This solution has been suggested to us by Elastic support. I think ECS schema will not be stable for a long time, so this is the solution to avoid a lot of collisions ... and angry users :)

Maybe this is also one way to avoid all collisions in future - add feature to beats, example dashboards, ... to allow to specify the prefix under all ECS fields could be stored.

**Comment by webmat** [comment]
Awesome, glad to know this makes sense as a way to work around the official field naming.

@vbohata Are you ok if we close this issue for now? I have created #114 to document the thinking outlined above.

**Comment by vbohata** [comment]
Yes, thanks.
