### ISSUE TITLE
Unreleased v1.7, but CHANGELOG.md has v1.7

### ISSUE THREAD

**Issue by patoi** [elastic/ecs#1108]
**Description of the issue:**
Ambiguous release v1.7 Is it released or not?

CHANGELOG.md contains information about v1.7, but GitHub Release doesn't contain it, and ECS homepage is refer to v1.6 as "stable" release.

**Any additional context or examples:**

**Comment by webmat** [comment]
Hello, thanks for raising this.

ECS releases are published using the [Github Releases feature](https://github.com/elastic/ecs/releases). 

ECS 1.7 is not released yet, but it will be soon. It's currently in feature freeze, so that's why there's 1.7 showing up in a few places.

The longer feature freeze period for ECS is a recent change to our procedures. This feedback is useful, we'll see if we can make things clearer.

Thanks!
