### ISSUE TITLE
Add Alternate Data Stream Name to File Events

### ISSUE THREAD

**Issue by Samirbous** [elastic/ecs#1285]
**Summary**

A category of [malwares](https://blog.malwarebytes.com/101/2015/07/introduction-to-alternate-data-streams/) tend to leverage file alternate data stream content to store malicious code in an attempt to avoid AV file system scan. The file name will contain a colon ":" symbol and for rules creation or simply searches it become an expensive operation as one need to add prefix wildcards to file.name:*\:* 

Below an example of how the ADS file name looks like: 

![image](https://user-images.githubusercontent.com/64742097/109820106-fc6bd100-7c34-11eb-93aa-b6124024286e.png)

We need an [ECS field](https://www.elastic.co/guide/en/ecs/current/ecs-file.html) that captures this info (e.g. file.alternate_data or file.ads)

**Motivation**:

**Detailed Design**:

Provide additional details around the design of the proposed changes.

* Field names
* Example values for the fields
* Suggested appropriate datatypes
* Any example events that map to the proposed use case(s)

**Comment by rw-access** [comment]
This field is only relevant to Windows and is an NTFS thing. I don't think that precludes it from ECS and just needs to be documented. Here's the relevant [NTFS wiki page](https://en.wikipedia.org/wiki/NTFS#Alternate_data_streams_(ADS))

There's some overlap with `file.name` and I think we should be clear what belongs in the name and what belongs in a new field, like `file.ads`. For the above path `C:\temp\notepad.vbs:adstest.exe`, which contains an alternate data stream:


* `file.path`: `C:\temp\notepad.vbs:adstest.exe`, includes the full path
* `file.name`: `notepad.vbs`, does not include the ADS
* `file.extension`: `vbs`, includes the extension
* `file.ads`: `adstest.exe` the alternate data stream name. There's really no concept of extensions within an ADS. Often they are something like `$Data` (default) or `Zone.Identifier`

For a Windows path without an alternate data stream, such as `C:\Windows\system32\cmd.exe`:

* `file.path`: `C:\Windows\system32\cmd.exe`, includes the full path
* `file.name`: `cmd.exe`
* `file.extension`: `exe`, includes the extension
* `file.ads`: missing from the event

Since this is a minor change, I don't think it needs to go through the RFC process. @ebeahan do you have any hesitations to this request? If not, I'll move forward with a PR

**Comment by ebeahan** [comment]
No, I don't think an RFC is necessary for a single field. I do have some hesitation in using the acronym `ads` for the field name over fully expanding `file.alternate_data_stream`.

I'm not very familiar with this area at all, so this is just an observation. ADS is the NTFS/ReFS implementation of a [forked file structure](https://en.wikipedia.org/wiki/Fork_(file_system)). Do we think we'd ever want to capture this concept generically? Seems unlikely, since the immediate application is related to identifying malware and threat hunting on Microsoft platforms, but it was just a thought.

Would a single file ever need to capture multiple stream names, and if so, should this new field expect to contain an array of values?  Or will it always be 1:1?

**Comment by rw-access** [comment]
TIL about the file forking.
And yes there can be multiple data streams on a Windows file.

Although it can have multiple streams, typically with endpoint telemetry (Endgame, Elastic Endpoint, Sysmon, File eat, etc.) you see things on an event by event basis. So you'd only operate on one ADS at a time. Similar to how a folder could have multiple files, but we deal with one at a time in the file.* field set.

I'm on board with making this generic and os-inclusive. What do you have in mind for the name? Naming is hard.

**Comment by ansell** [comment]
Mac systems have "Resource Fork" and "Data Fork" as two separate components of a file.

**Comment by rw-access** [comment]
Thanks @ansell. Good distinction.

Is `fork_name` a good generic name for the field that encompasses everything?
