### ISSUE TITLE
[Docs] Add link to list of generated fields

### ISSUE THREAD

**Issue by djptek** [elastic/ecs#1313]
**Summary**

Consider adding a reference to 

https://github.com/elastic/ecs/blob/v1.8.0/generated/csv/fields.csv

in Docs

**Motivation**:

When mapping a data source to ECS it might be useful for some users to start by looking at the list of generated fields. Would it be useful to add a link to this resource in Docs?

**Comment by jamiehynds** [comment]
Great idea @djptek - users regularly ask for an easy way to browse through ECS fields. More often than not, they aren't aware of the CSV file due to its location on Github. 

I'm open to suggestions, but maybe a link at the top of the E[CS Field Reference](https://www.elastic.co/guide/en/ecs/current/ecs-field-reference.html), makes the most sense?

**Comment by djptek** [comment]
@jamiehynds do you think it would be best to have a simple link to the CSV in GitHub (lo-cost) or better rendered in a table as a distinct HTML page in docs?

**Comment by jamiehynds** [comment]
@djptek I'd lean towards a link to the CSV - feedback has always been positive on that CSV, once folks are pointed to it. Plus it's updated with each ECS release, so reduces the overhead vs keeping a table within docs up to date.

**Comment by ebeahan** [comment]
Chatted about this a bit out-of-band, so I'll just summarize a few points that came up:

* The CSV does contain all the full list of fields (including all the nestings), but it is still a bit raw compared to the field reference docs. One example is the CSV only contains the `short` field descriptions which are less detailed than what a user would find in the docs.
* Since the CSV will update with each schema change, we'd need to pin the current version the users viewing to the correct version of the CSV. This does introduce some additional complexity into the implementation as well as introduces more possible of broken links failing the docs build if anything gets shuffled around. Any unreleased versions won't match up exactly with the selector from the docs (`1.9` => `1.9.0-dev`, `1.x` => `1.10.0-dev`, `master` => `2.0.0-dev`)
* We do already have a mention of the CSV and other artifacts in the `Generated Artifacts` section. Perhaps we call attention to how the CSV could be used as a single-page reference to that section but leave the generic GitHub link?
* There's been past discussion (#446, #448) to list all the ECS fields on a single page in the docs for users who prefer to Ctrl/Cmd + F their way around. There are definitely pros/cons to the current implementation as there are pros/cons to a single page. Though, with changes coming to the docs site in the near future, I don't think it's necessary to evaluate making any large refactoring to the ECS field docs today.

**Comment by djptek** [comment]
@ebeahan I have this building OK with a pointer to the CSV but as you quite rightly point out the docs for e.g. `2.0.0-dev` will have a reference to `master` which is not good. Perhaps, I could add some logic to parse versions or should we reconsider a new docs page?

**Comment by ebeahan** [comment]
Could detail be added to the existing `Generated Artifacts` docs section [here](https://www.elastic.co/guide/en/ecs/current/ecs-artifacts.html) to improve the discoverability of the CSV (or any other generated artifact) while not introducing complexity into the ECS docs by linking directly?

**Comment by djptek** [comment]
Good news, bad news

I agree the `Generated Artifacts` has a lot of potential for enhancement by expanding e.g. `Elasticsearch index templates, CSV, and Beats field mappings` to provide a brief description of what there are and where to find them

Unfortunately, this page already exhibits the version offset issue, so the `current` page is within the `1.9` docset while referencing the `master`Github

That's an issue in `index.asciidoc` - I've opened a separate PR for that here https://github.com/elastic/ecs/pull/1338 let's discuss that and then revisit here

**Comment by kgeller** [comment]
Implemented in #1317 , closing this issue
