### ISSUE TITLE
Change all 45 occurrences of `nested` in docs to `enclosed` or `inner` or `sub-` to avoid misdirecting users to `type: nested`

### ISSUE THREAD

**Issue by djptek** [elastic/ecs#1358]
**Summary**

Review and potentially change all 45 occurrences of `nested` in docs to `enclosed`, `inner`, `sub-` of similar to avoid potential for users to use `type: nested` where not appropriate. This was a non-issue prior to the availability of `type: nested` - now that https://github.com/elastic/ecs/issues/1225 is closed this should be addressed

**Motivation**:

The documentation uses the overloaded term `nested` liberally to refer to: 

- sub-fields, which is debatable
- inner objects, which is common industry usage, e.g. see [Introducing JSON](https://www.json.org/json-en.html), but unfortunately is liable to create confusion and increase processing and storage costs if interpreted as `type: nested`

I suggest to replace all occurrences of `nested` in the docs with an alternative such as `enclosed` or `inner` or `sub-` to ensure end users don't make use of `type: nested` excepting where this is beneficial to them

I acknowledge that `nested` was used in these contexts because it is more readable & succinct than many of the alternatives, however, this is technical documentation so I think pedantry is warranted

**Detailed Design**:

Examples of usage of `nested` outside the context of `type: nested` in the docs: 

_The `as` fields are expected to be nested at: `client.as`, `destination.as`, `server.as`, `source.as`_

_Field sets that can be nested under Destination_

_The document structure should be nested JSON objects._

_If you're ingesting to Elasticsearch using the API, your fields must be nested objects, not strings containing dots_

Alternatives:

_The `as` fields are expected to be *subfields* of: `client.as`, `destination.as`, `server.as`, `source.as`_

_Destination can *include* the following Field sets_

_The document structure should be nested JSON objects._  **I think this one is OK as is**

_If you're ingesting to Elasticsearch using the API, inner objects or sub-fields should be enclosed within curly braces, rather than strings containing dots._  **borderline, so I suggested an alternative anyway**

Note on Parent/Child: this is strongly contraindicated as an alternative as that will only serve to create false expectations for SQL specialists and/or drive users towards `type: join`

**Comment by ebeahan** [comment]
Thanks, @djptek, for putting these thoughts together. Now that `type: nested` fields are starting to be introduced, it makes sense to review terminology and consider if we can better convey the concepts. 

I think `subfields` could be a good alternative.  The current docs use `field reuse` when describing nesting fieldsets, so using `field reuse` in place of `nested` when detailing field reuse could be another option.

Example: "_The `as` fields are expected to be reused at..._"

> The document structure should be nested JSON objects. I think this one is OK as is

When trying to describe the expected structure of JSON objects, I think we should continue to use nested. Since `nested` is often used to describe objects within a parent JSON object, I feel like we should align with the convention.

Previously, there was a [note](https://www.elastic.co/guide/en/ecs/1.4/ecs-faq.html#notation-diff) in the ECS docs to help clarify that JSON nesting was not referring to the nested type. We removed the notice since using `type: nested` was being considered in the near term, but now maybe we consider adding a section clarifying the two types of `nesting` found around ECS.

**Comment by djptek** [comment]
I'm pondering a third way... the problem with terminology is actually upstream, Elasticsearch's use of `nested` is the root cause. I'm thinking through raising an issue in the Elasticsearch Repo to address this in the docs, maybe ask to change that to `synchronous nested` or similar, not in the code, simply in the description, to avoid ambiguity. _a pedant is seldom, if ever, wrong_

re `subfields` I think that works best for fields of an object, that's to say where each field is a leaf on the document map. Nesting isn't applicable there anyway since those or properties of an object, not an object inside an object. So I'll raise a PR to address these anyway

**Comment by djptek** [comment]
>>Previously, there was a note in the ECS docs to help clarify that JSON nesting was not referring to the nested type.

I like this, so maybe any &/all potentially ambiguous usages of `nested` could simply be a hyperlink to a disambiguation page with a brief explanation and which in turn links to https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html & https://www.json.org/json-en.html

**Comment by djptek** [comment]
Closing as solving `nested` overloading is a wider topic beyond the scope of ECS
