### ISSUE TITLE
observer.mac, observer.name and others are redundant. host fieldset should be reused.

### ISSUE THREAD

**Issue by ypid-geberit** [elastic/ecs#1493]
**Description of the issue:**

What is typically the "host" of an event can become the "observer" for example in network monitoring. The following fields are redundant:

* observer.mac
* observer.ip
* observer.hostname
* observer.name

I propose to allow to reuse the host fieldset as "observer.host". This would be a breaking change.

Issues like #1455 also show the issue of this redundancy.

**Any additional context or examples:**

**Comment by ebeahan** [comment]
Thanks, @ypid-geberit, for the feedback. There are many common field names between `host.*` and `observer.*`.

In the ECS sense, `observer.*` isn't necessarily intended to be a type of `host`. An ECS `host.*` is the compute instance where an event happened or measurement was taken. An `observer.*` is a discrete system from a `host.*` whose events are generated from observing the activity of other hosts.

Since observers can be a range of compute instances, many observers have attributes shared with the `host.*` fieldset, like `hostname`, `ip`, etc. While reusing `host.*` underneath `observer.*` would add many of those fields, I think it also breaks the entity-relationship ECS establishes between the two.

I also think it introduces confusion for an `observer`, which also can act as a `host.*` (potentially with its own `agent`). Should details of an `observer` host go under `host.*` or `observer.host`? Should host metric details for an `observer.*` go under `observer.host.cpu.usage`? I'd prefer to have a single source, e.g. `host.cpu.usage`, for users to rely on for their aggregations and visualizations.

**Comment by ebeahan** [comment]
Closing for now. We can reopen if there's more to discuss.
