### ISSUE TITLE
The process.same_as_process boolean field does not show up in the ecs documentation.

### ISSUE THREAD

**Issue by mitodrummer** [elastic/ecs#1902]
**Description of the issue:**
The process.same_as_process boolean field does not show up in the ecs documentation.

It's defined in the yml:
https://github.com/elastic/ecs/blob/8.2/schemas/process.yml#L256

But does not show here:
https://www.elastic.co/guide/en/ecs/current/ecs-process.html

**Comment by kgeller** [comment]
@mitodrummer looks like another casualty of https://github.com/elastic/ecs/pull/1879 . Putting up a PR to fix shortly

cc @ebeahan

**Comment by kgeller** [comment]
@mitodrummer I was wrong. This comes down to us not having the `same_as_process` field on the process fieldset directly (due to the the subset filtering we implemented for the complex re-use nestings). Our tooling currently only outlines those top-level fieldset fields.

We have two options:
1) Make it so `process.same_as_process` exists as an actual field via that subset yml, and it'll be in the docs
2) Leave it as is, and have a gap in the docs

Note: this also impacts `process.entry_type.meta`
