### ISSUE TITLE
Filebeat logs source field as text and ECS as an object

### ISSUE THREAD

**Issue by latundetoks** [elastic/ecs#307]
"source": "/var/log/httpd/access.logs",
"src_ip":"192.168.2.1"

Conversion of the src_ip field to ecs terminates the logstash pipeline, since the source field is text and source.ip an object. The only options I can think of right now to solve this is to drop the `source` field before ingest. 

`echo '{"source":"/var/log/httpd/access.logs", "src_ip":"192.168.2.1"}' | /usr/share/logstash/bin/logstash -e 'input {stdin{codec => json_lines}} filter {mutate {rename => {"src_ip" => "[source][ip]"}}} output{stdout{codec => rubydebug}}'`

Any ideas here would be appreciated.

**Comment by webmat** [comment]
@latundetoks Yes, this is a breaking change between 6.x and the upcoming 7.0. I see two ways you can go about this.

1) You can do like the new Suricata module in Filebbeat. It aims to map to ECS, but was released in 6.x, so this is what we're doing with it:

* In 6.x, populate `source_ecs` instead of `source`, this avoids the mapping conflict, and Filebeat is free to populate `source` as it previously did.
* When migrating to 7.x, there will be field aliases for your visualizations/dashboards built around `source_ecs`, so during the your dashboards will keep working.
* After the 7.x migration, you can update your dashboards to use the "real" fields, under `source`.

2) Another approach you can take is for this specific event source, you could decide to output to a different index.

In doing so, you are free to rename the current `source` field to something else (e.g. `log.path`), and crafting your events with the `source` field set, as defined in ECS.

If you do this, however, you then need to adjust and curate your index template yourself. You can change your output index with [Ingest Node's date index processor](https://www.elastic.co/guide/en/elasticsearch/reference/current/date-index-name-processor.html) or in Logstash, by adjusting the [index option of the ES output](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-index).

**Comment by webmat** [comment]
Closing this, as there were no further comments. Feel free to reopen if you'd like to discuss further.
