### ISSUE TITLE
Netapp audit event ecs mapping considerations

### ISSUE THREAD

**Issue by willemdh** [elastic/ecs#312]
I'm in the process of migrating our NetApp audit events to ECS. Found a place for every field, except for the event where a file or directory is renamed.

It seems `file.target_path` exists, but the doc says it's meant for symlik targets, so for now I created `file.path_new`.

Example:

```
{
  "_index": "netapp-002-2019.01.29",
  "_type": "doc",
  "_id": "rqIDmmgB6pwhRqiLJ4Yx",
  "_version": 1,
  "_score": null,
  "_source": {
    "event.category": "Object renamed/moved",
    "@version": "1",
    "netapp.svm": "svm_002",
    "file.path_new": "(vol_br01);/Data/Administratie/Balie/A. Nieuwe structuur Onthaal & balie/3. BESTELLINGEN/Economaat (Staples)/Staples 2018/2018",
    "user.name": "bochan",
    "@timestamp": "2019-01-29T14:28:44.253Z",
    "client.ip": "1.54.50.149",
    "client.domain": "MYDOMAIN",
    "file.inode": "Nieuwe map",
    "event.action": "Renamed,Moved",
    "event.id": 9999,
    "type": "netapp-audit",
    "netapp.volume": "vol_br01",
    "user.id": "S-1-5-21-171585296-3921855-1598175747-73842",
    "file.path": "(vol_br01);/Data/Administratie/Balie/A. Nieuwe structuur Onthaal & balie/3. BESTELLINGEN/Economaat (Staples)/Staples 2018/Nieuwe map",
    "event.created": "2019-01-29T14:33:48",
    "file.type": "dir",
    "observer.hostname": "oobserver-server"
  },
  "fields": {
    "@timestamp": [
      "2019-01-29T14:28:44.253Z"
    ],
    "event.created": [
      "2019-01-29T14:33:48.000Z"
    ]
  }
}
```

So can we reuse `file.target_path` to place renamed file names, or is there room for somethijng like `file.path_new`? The NetApp audit events are inserted with a custom ps1 script we wrote to parse the evtx files generated by our NetApp. 

I'm also wondering about `event.id`, as the ecs docs say it should be unique? But the NetApp audit events can be any of 4 Winodws eventlog event id's, `4656`, `4659`, `4660 `or `9999`. Where will WIndows eventlog event id's be saved in ecs?

Found 2 NetApp specific fields for which I created
```
netapp.svm
netapp.volume
```

**Comment by webmat** [comment]
You're right that target files (and target users for that matter) haven't been addressed yet in ECS, it's on our growing list of things to address soon. In the case of files, I'm wondering if we shouldn't use `target.file` instead. This would let us capture other things than file copy/rename operations, but also changes to metadata (mode, ownership).

I've been working on translating Winlogbeat recently, and I came up with the same issue, with the Windows event ID. This hasn't been discussed more broadly yet, so take what I say with a grain of salt. I see two ways forward on this:

* I'm thinking that `event.id` is perhaps too constrained. Should we let the semantics of `event.id` match with the event source's semantics instead?
* The other option would be to introduce a field to match Windows' semantics, perhaps `event.code`. This `.code` would be useful for any other source that has both an identifier and a text representation for their messages.

Now that I spell it out, I think I prefer the latter of the two ;-)

What do you think?

**Comment by webmat** [comment]
The custom fields should be fine. 👍

**Comment by willemdh** [comment]
@webmat First of thanks for your fast response and suggestions. Being a Windows admin for 12 years and working with Windows eventlog monitoring for 8 years, I must honestly say that naming a Windows eventlog event id field anything else then `event.id` or `event.win_eventlog_id` (sth without event and id in the name) will be very confusing for the standard Windows administrator. 

![image](https://user-images.githubusercontent.com/6462991/51965336-81d69300-2469-11e9-8a22-16fc0f88b01f.png)

Checked the Splunk docs to see how they are doing it and they seem to also use `EventCode` apparently. Still, my preference would go to `event.id` or another proposal field containing the word event and id. I'm interested to see how you will call the other WIndows eventlog fields in ecs, do you have a link to the pull request or issue where you are working on the conversion to ecs?

**Comment by willemdh** [comment]
Found it => https://github.com/elastic/beats/pull/10333#discussion_r252111691

When I find some time I'll try to have a look at what's going on there.

**Comment by webmat** [comment]
Time is running short for the 7.0 feature freeze, actually; it's next week ;-) So now's the time, if there's a few things that have always bugged you about Winlogbeat (if you use it?).

My understanding at this time, is that there's quite a bit of juicy data that would be a great fit to map to ECS inside EventData, but that this part of the logs is really source-specific. This unfortunately means we probably won't have the time to carefully review these sources, to ensure the mapping is always correct. If there's rules of thumbs that could help determine for example that EventData.TargetUserSid can always map to user.id, that's great. But if on the other hand, EventData.IpAddress is not always the source address, then we just won't touch it yet. Better not migrate something than do an incorrect migration.

For my part, looking at Winlogbeat for the first time since last week, I've found the field naming a bit confusing: for example, channel is called log_name, and provider name is called source_name. So I while understand the frustration in seeing familiar concepts getting a different name in a given solution, it's bound to happen, when developing such a schema. So we'll see on event.code. Perhaps option 1 above will prevail after all :-)

**Comment by willemdh** [comment]
Next week already ^^.. (I'm still working on getting my multi-tenant Kibana Container 6.4.3 setup to the new Spaces in 6.5.x, you guys are going so fast lol)

Yes I'm using Winlogbeat on a lot of servers. What bugs me in Winlogbeat is that, as you  also say: 

> "This unfortunately means we probably won't have the time to carefully review these sources, to ensure the mapping is always correct"

There are so many undescriptive fields. Each eventlog generating component or applications seems to log different stuff to these fields. Of course that's not per sé a Winlogbeat issue, but a Windows issue.. Windows eventlogs are just annoying to work with..

![image](https://user-images.githubusercontent.com/6462991/52074120-75e1f280-2589-11e9-968a-21e281f4b0dd.png)

Checked some event_data.IpAddress

```
::ffff:5.5.28.156
::ffff:5.5.28.154
```
not sure if the :ffff will casue a mapping conflict?

Also it seems there are three variations of ipaddress:

![image](https://user-images.githubusercontent.com/6462991/52074599-86df3380-258a-11e9-9390-c6bce68c3f10.png)

Grtz

**Comment by webmat** [comment]
OMG that IpAddress inconsistency has to be pretty annoying, haha! Good to know, though. I'll see if I can address that in my 7.0 update.

The IP addresses above are IPv6 representations of IPv4's, afaict. They're fine. You can test this out:

```
PUT ip_test
{
  "mappings": {
    "_doc": {
      "properties": {
        "address": {
          "type": "ip"
        }
}}}}
PUT ip_test/_doc/1
{ "address": "::ffff:5.5.28.156" }
GET ip_test/_search
```

**Comment by willemdh** [comment]
Seem it's even worse then I thought => When I look for 'dress', I can find even more ip address related fields.... => 

![2019-02-01_08-30-56](https://user-images.githubusercontent.com/6462991/52108913-f93c2c00-25fb-11e9-9ede-1fd58c11f213.gif)

Although not all of them seem to exist at this time when apply an exist filter.

On first sight the ip address fields seem indeed all different then the host.ip. Also found quite a few which have '-' as value.

**Comment by webmat** [comment]
Yeah I've found another source that will help me make sense of what's in there as well.

Although it's looking like the imminent "ECS update" will not tackle this. The deep event shaping should not be happening in the agent itself (especially not dealing with gray areas like this). Because any improvement to the event shaping now translate to a full rollout of Winlogbeat again. Not great ;-)

So the "ECS update" will more likely set the stage to send straigthforward Windows Log events that can then be shaped up with Ingest Node (as Filebeat modules do). Although the infrastructure for that is not yet in place...
