### ISSUE TITLE
url.port is type integer whereas all other *ports are type long

### ISSUE THREAD

**Issue by Phillip-Gabler** [elastic/ecs#342]
The url.port is type integer whereas all other *ports are type long. Is this intentional?

**Comment by webmat** [comment]
No, it's a mistake: https://github.com/elastic/ecs/pull/339 ;-) We'll adjust and have it be a long for consistency.

But you can use either, this difference is immaterial. Since the potential port values only go up to 65k and signed ints are -2B to 2B, using one or the other will not affect your ability to query the fields in any way. It won't even show up as a conflict in a Kibana index pattern :-)
