### ISSUE TITLE
What fields to use for message driven application logs?

### ISSUE THREAD

**Issue by jordanjennings** [elastic/ecs#436]
We have a number of applications that use queues and pass messages around and I'm wondering if there's somewhere already defined that would be relevant for logging things like:

- received message type
- received message data summary (because messages are usually too big to log fully)
- outgoing message type
- outgoing message data summary (for size again)

I see there are `event` fields which are somewhat related, because there's obviously some conceptual overlap between events and messages (in the context of an event-driven system vs message-driven system). However, I don't see anything applicable for the things I'd like to log. I do see `event.type` but the docs say not to use it. I also see `event.original` but for messages the body is often too large to log so using that field doesn't quite make sense. It could make sense to use `event.action` to log something like `received-message` and `sent-message`, if there were a place to put the type and the message summary like I'm looking for.

Using the `message` field to log a summary is a possibility but it feels wrong because the `message` is usually a brief readable message, as opposed to a big chunk of data. For example, let's say we have a message from the queue that is 256KB, we might produce a condensed form of the message body strictly for logging that is 2KB, and putting that in the `message` field doesn't seem right.

Have I missed any fields appropriate for this? What are the thoughts around this use case?

**Comment by webmat** [comment]
Hey @jordanjennings, without knowing too much about your specific use case, I think I can still make a few suggestions.

- `message` can be used for your summary, IMO. The purpose of the field is to give a human readable representation of the message, event if it's pretty long. Even a purely structured log source could (should ideally) have a `message` field crafted based on what the message captures.
  - To support using `message` for even a 2kb summary: Winlogbeat passes along the message body in `message`. Windows event messages are typically multiline, and can easily go over 2kb in size. So I don't think this size range is a problem.
- I don't think you should necessarily create two sets of fields for sent and received. I suggest using a field to indicate the direction of the message (as you hint at, with `event.action`).
- You're right that currently ECS doesn't address your use case directly. But this should not stop you from using ECS. You can add custom fields to your events.
  - You should use as many ECS fields as you can for what maps well, like network addresses, `message`, `@timestamp`, etc.
  - The rest should be added in custom fields. This is your best option to capture what you would like to map to the reserved fields like `event.action` and for all fields that have no clear mapping.
  - Once you have this log source modelled, you could make a proposal to add support in ECS for message-based applications.

Now there's a bit of a thought process that we need to capture and document better, for how to add custom fields without risking conflicts with future developments of ECS. But here's the gist of it:

- For the simplest cases, the ECS field `labels` field may be enough (I don't think that's the case here)
- You may create leaf fields directly under existing ECS field sets (e.g. `event.raw_action`).
  - This is not recommended because there's a risk a conflicting field gets added in the future.
- If you need a proper custom field set:
  - You'll want to avoid using generic words for the name of the field set where you nest your custom fields, in case this gets added to ECS in the future.
  - In ECS we avoid brand names (companies, technologies, etc). So nesting under a brand name should be relatively safe.
    - Although nesting under a technology directly may conflict at query time with other sources. E.g. Beats nests Apache HTTPD metrics and logs under `apache.access`.
    - Safest is to nest all custom fields under your company name. E.g. `acme.msg.*`
  - ECS uses lowercase & underscores exclusively for field names. So custom fields using capitalized names should be safe.

These are just some ideas, you may find other clever ways to avoid conflicts (if so, let us know).

Finally, some naming conflicts may turn out not to be a big deal in the end:

- We may independently add the same field with the same semantics as yours: 🎉 
- We may add a field or field set of the same name as yours, but used differently
  - If that's the case, but you never query sources that use both conflicting definitions at the same time, it's not a pressing issue to fix.
  - If this is a legit conflict, then this will be more painful. You can migrate your custom fields by duplicating the field for a while in your source/pipeline (or using ES field aliases), then migrating all consumers of these new fields (dashboards, ML jobs, API clients). Then once the conflict is resolved, you'll be able to update your pipeline to use later ECS versions.

Hope this helps. Happy to discuss further if you have other things in mind.

**Comment by webmat** [comment]
Closing this for now. You're welcome to open other issues, as needed :-)
