### ISSUE TITLE
Issues maintaining a forked ECS repo

### ISSUE THREAD

**Issue by nick-george** [elastic/ecs#443]
Hi there, 

My understanding is that you expect users of the ECS to fork it in order to add their own schemas/fields (for personal use), although I haven't found any documentation stating this exactly. I have forked the repo, and am having serious issues merging upstream changes into my repo. The main reason for this is because you're storing all the build artefacts in the repository. Is there any particular reason why you're storing all the build artefacts in here (the files generated by 'make')? 

Below is an example of me merging in the current v1.0.0 branch on top of the changes I made against the beta2 tag. 

In general, how would you recommend users of the ECS maintain their own version? 

Cheers, 
Nick

> $ git merge ecs/1.0
Auto-merging version
CONFLICT (add/add): Merge conflict in version
Auto-merging scripts/tests/test_schema_reader.py
CONFLICT (add/add): Merge conflict in scripts/tests/test_schema_reader.py
Auto-merging scripts/tests/test_es_template.py
CONFLICT (add/add): Merge conflict in scripts/tests/test_es_template.py
Auto-merging scripts/tests/test_ecs_spec.py
CONFLICT (add/add): Merge conflict in scripts/tests/test_ecs_spec.py
Auto-merging scripts/schemas.py
CONFLICT (content): Merge conflict in scripts/schemas.py
Auto-merging scripts/schema_reader.py
CONFLICT (add/add): Merge conflict in scripts/schema_reader.py
Auto-merging scripts/requirements.txt
CONFLICT (content): Merge conflict in scripts/requirements.txt
Auto-merging scripts/generators/intermediate_files.py
CONFLICT (add/add): Merge conflict in scripts/generators/intermediate_files.py
Auto-merging scripts/generators/es_template.py
CONFLICT (add/add): Merge conflict in scripts/generators/es_template.py
Auto-merging scripts/generator.py
CONFLICT (add/add): Merge conflict in scripts/generator.py
Auto-merging scripts/cmd/template/template.go
CONFLICT (add/add): Merge conflict in scripts/cmd/template/template.go
Auto-merging schemas/user.yml
CONFLICT (content): Merge conflict in schemas/user.yml
Auto-merging schemas/url.yml
Auto-merging schemas/server.yml
CONFLICT (content): Merge conflict in schemas/server.yml
Auto-merging schemas/related.yml
CONFLICT (content): Merge conflict in schemas/related.yml
Auto-merging schemas/observer.yml
CONFLICT (content): Merge conflict in schemas/observer.yml
Auto-merging schemas/host.yml
CONFLICT (content): Merge conflict in schemas/host.yml
Auto-merging schemas/file.yml
CONFLICT (content): Merge conflict in schemas/file.yml
Auto-merging schemas/event.yml
CONFLICT (content): Merge conflict in schemas/event.yml
Auto-merging schemas/ecs.yml
CONFLICT (content): Merge conflict in schemas/ecs.yml
Auto-merging schemas/cloud.yml
Auto-merging schemas/client.yml
CONFLICT (content): Merge conflict in schemas/client.yml
Auto-merging generated/legacy/template.json
CONFLICT (content): Merge conflict in generated/legacy/template.json
CONFLICT (rename/delete): generated/legacy/schema.csv deleted in ecs/1.0 and renamed in HEAD. Version HEAD of generated/legacy/schema.csv left in tree.
Auto-merging generated/elasticsearch/7/template.json
CONFLICT (add/add): Merge conflict in generated/elasticsearch/7/template.json
Auto-merging generated/elasticsearch/6/template.json
CONFLICT (add/add): Merge conflict in generated/elasticsearch/6/template.json
Auto-merging generated/csv/fields.csv
CONFLICT (add/add): Merge conflict in generated/csv/fields.csv
Auto-merging fields.yml
CONFLICT (content): Merge conflict in fields.yml
Removing docs/use-cases-header.md
CONFLICT (modify/delete): docs/intro.md deleted in ecs/1.0 and modified in HEAD. Version HEAD of docs/intro.md left in tree.
Auto-merging docs/index.asciidoc
CONFLICT (add/add): Merge conflict in docs/index.asciidoc
CONFLICT (modify/delete): docs/implementing.md deleted in ecs/1.0 and modified in HEAD. Version HEAD of docs/implementing.md left in tree.
Auto-merging docs/glossary.asciidoc
CONFLICT (add/add): Merge conflict in docs/glossary.asciidoc
Auto-merging docs/fields.asciidoc
CONFLICT (add/add): Merge conflict in docs/fields.asciidoc
Auto-merging docs/faq.asciidoc
CONFLICT (add/add): Merge conflict in docs/faq.asciidoc
Auto-merging docs/contributing.asciidoc
CONFLICT (add/add): Merge conflict in docs/contributing.asciidoc
Removing docs/about.md
Auto-merging code/go/ecs/version.go
CONFLICT (add/add): Merge conflict in code/go/ecs/version.go
Auto-merging code/go/ecs/user.go
CONFLICT (add/add): Merge conflict in code/go/ecs/user.go
Auto-merging code/go/ecs/url.go
CONFLICT (add/add): Merge conflict in code/go/ecs/url.go
Auto-merging code/go/ecs/network.go
CONFLICT (add/add): Merge conflict in code/go/ecs/network.go
Auto-merging code/go/ecs/host.go
CONFLICT (add/add): Merge conflict in code/go/ecs/host.go
Auto-merging code/go/ecs/ecs.go
CONFLICT (add/add): Merge conflict in code/go/ecs/ecs.go
Auto-merging code/go/ecs/base.go
CONFLICT (add/add): Merge conflict in code/go/ecs/base.go
Auto-merging code/go/ecs/agent.go
CONFLICT (add/add): Merge conflict in code/go/ecs/agent.go
Auto-merging README.md
CONFLICT (content): Merge conflict in README.md
Auto-merging Makefile
CONFLICT (content): Merge conflict in Makefile
Auto-merging CONTRIBUTING.md
Auto-merging CHANGELOG.md
Automatic merge failed; fix conflicts and then commit the result.

**Comment by webmat** [comment]
Hey @nick-george, it's actually not expected that people maintain a fork of the ECS repo to maintain their custom templates.

We do want to adjust the generator to be able to take user's external definitions, to provide a sensible workflow around this. We have an issue for it at #324, also discussed in #410. But we haven't gotten around to implementing that yet. In the meantime perhaps you can try our default template + overriding it with separate templates, with [multiple template matching](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html#multiple-templates), aka the `order` setting.

This is not a perfect solution, because the sample template is made to match the pattern `ecs-*`. Naming your indices that way is not a prerequisite for ECS compatibility. The ideal way for your consumers (dashboards, apps, etc) to query your ECS indices will be by explicit index naming: index pattern, a list like `GET index1,index2-*/_search` or index aliases. I'm adding this bit of information because when comes time to depend on specific ECS versions -- as ECS continues to mature -- an index naming scheme would become very clumsy\*. When we get to this, the expectation on querying your ECS sources will be to also use the `ecs.version` field in your queries, if you only want sources that support recent additions to the schema.

Finally, I agree that storing the artifacts in the repo is less than ideal. I also have to deal with this quite often ;-) It's also on the list of things to improve. But since it's not expected that the community has to deal with this much, it's lower on the priority list.

\* Imagine what the name of a Filebeat 7 index would look like: `ecs-1.1.0-filebeat-7.1.0-YYYY-mm-dd` ;-)

**Comment by webmat** [comment]
Oh, I wanted to mention. Of course if you're willing to take a stab at implementing this support for external field definitions in the generator, that would be most welcome.

**Comment by nick-george** [comment]
Thanks for the clarification @webmat and sorry it took me so long to reply. OK, good to know you don't expect users to maintain a fork (I would be more than happy to however, provided derived objects weren't in the repo). 

I like the idea of being able to specify external schema files during the build. I'll also have a look at the use of multiple templates. I wonder how that will git into our Logstash configuration. 

I didn't really like the way the ECS template specified ecs-* as the index name, so as part of our build process, we change it to the index alias we're using for all event data ("events"). I haven't done too much thinking about how we will handle major changes in the ECS later. Maybe we'll re-index everything. 

Thanks again, 
Nick

**Comment by ypid-geberit** [comment]
For me, maintaining a "fork" of some sort came natural to me for the following reasons:

* Ability to easily contribute back/upstream changes/new fields to Elastic. This is as simple as `git cherry-pick` if a change has proven itself internally.
* Be able to maintain a patchset ontop of ECS releases that are eventually upstreamed/released and then dropped from my patchset. Use the power of `git rebase`.
* Have only one documentation.

See https://github.com/geberit/elastic-ecs#organization-internal-use-of-ecs for the details.
