### ISSUE TITLE
http status reponse code mapping

### ISSUE THREAD

**Issue by willemdh** [elastic/ecs#449]
Hello,

While looking into some mapping issue in '*' index pattern on 1 of my clusters on 6.7.1, I noticed that

`apache2.access.response_code` , which is an alias to `http.response.status_code` is defined as a long type. Imho things like status codes should be of type keyword? 

The mapping problem I have is related to the Apache2 machine learning setup:

![image](https://user-images.githubusercontent.com/6462991/57300093-5e5d5d00-70d6-11e9-9a44-db384ca1659b.png)

which created

```
  ".ml-anomalies-shared" : {
    "mappings" : {
      "doc" : {
        "apache2.access.response_code" : {
          "full_name" : "apache2.access.response_code",
          "mapping" : {
            "response_code" : {
              "type" : "keyword"
            }
          }
        }
      }
    }
  },
```

Resulting in:

![image](https://user-images.githubusercontent.com/6462991/57300156-82b93980-70d6-11e9-9b6f-a2f58df261ad.png)

**Comment by webmat** [comment]
Well a `*` index pattern will inevitably turn up some conflicts, especially with system indices that are not necessarily always meant for direct consumption, and therefore aren't kept aligned with the rest of the stack as fast as what's user-facing.

You're right that in general status codes and various general IDs should be `keyword`. Although for HTTP we made the call that the HTTP status codes had always been numeric, and would likely remain so as well. So my thinking is rather that this ML schema will eventually migrate to ECS instead.

Instead of creating a `*` index pattern, I'd recommend creating an index alias that scoops up specifically your index patterns that are expected to follow ECS. This will avoid problems like what you're observing with system indices.

**Comment by willemdh** [comment]
"Instead of creating a * index pattern, I'd recommend creating an index alias that scoops up specifically your index patterns that are expected to follow ECS. This will avoid problems like what you're observing with system indices."
Already working on that. Just to add, on * I'm seeing 25 mapping conflicts, which is reasonable considering the amount of data. As you suggest it was decided to keep http status code of numeric type, I'll close this.
