### ISSUE TITLE
user agent?

### ISSUE THREAD

**Issue by willemdh** [elastic/ecs#46]
Looking at for example this log:

![image](https://user-images.githubusercontent.com/6462991/42633846-efb996a0-85e1-11e8-9a28-078efa0721c3.png)

Would I ideally place this under user_agent.* or immediately under host.* object?

And what with:
- activex_support
- plugin_support
- ui_mode

**Comment by webmat** [comment]
I'm not sure we should define environment/OS specific fields in ECS (`activex_support`), although that doesn't prevent someone to augment their events with exactly that field anyway. It's just not part of the standard.

Not sure what `plugin_support` refers to.

But in any case, I think placing all of this under `user_agent` makes most sense, rather than `host`. `user_agent` is meant to describe an agent accessing your systems, whereas `host` is meant to describe your own actual systems :-) From the POV of the F5, which may be in the middle of two of your devices (workstation on your network => your internal server), I would keep this in `user_agent`, because the event describes a request where the requester describes themselves with a the user_agent string.

I would be inclined to use `host` in a setting where this is an event about a host. Like a host rebooting, that mentions it's a `Win7`.

**Comment by willemdh** [comment]
> although that doesn't prevent someone to augment their events with exactly that field anyway. It's just not part of the standard.

Totally understand. Thanks for clarifying.
