### ISSUE TITLE
hash.* fields are not well searchable

### ISSUE THREAD

**Issue by vbohata** [elastic/ecs#484]
Hash.* fields are not much universal. Lets imagine there will be thousands of file fields, some of them having file.hash.md5, some file.hash.sha512, ... It is not good for searching, aggregations, ... There should be some universal field like "hash.all" for keeping all the hashes or "hash.value" for keeping some of the hash.

**Comment by webmat** [comment]
Yeah hashes are tricky. One may have threat feeds using different hashes. So affording the ability to calculate and store more than one hash is important.

In order to simplify the use case of "just searching for a hash", I would recommend adding all hashes to an array in `related.hash`, so searches are straightforward. They're always `related.hash: ...`, no matter what kind of hash you have on your hands.

By the way, this is the intended purpose of the `related` field set. Re-reading the field set definition, it may not be obvious enough. But the idea of the field set is that anything that is repeated more than once on an event can be concatenated in an array, under `related.*` to facilitate search & pivoting.

The field set already defines `related.ip`. When we got `hash.*` in, it was always the intention to also add `related.hash` as well. Hasn't been added yet, though.

But then anything else you encounter that has this property (present in more than one place in your events) can and should also get a place under `related.`, for the same purpose. Another one that comes to mind is `related.user`. I'm sure we could list more.

**Comment by vbohata** [comment]
Is not better to include hash scheme as part of the value instead of defining tens of possible hash subfields for used hash algorithms? Like dovecot way: https://doc.dovecot.org/configuration_manual/authentication/password_schemes/

So instead of "hash.sha256", there could be just "hash" or "hashes" with value "{SHA256}myhash".
This saves mapping space + still gives the good way for filtering for specific hash type (especially in case of "hashes" field with the possibility to store multiple hashes) + is very nice if we do not know the hash function (in this case the "hashes" field will store just "myhash").

**Comment by ebeahan** [comment]
`related.hash` was added in https://github.com/elastic/ecs/pull/711
