### ISSUE TITLE
Client fields documentation is a bit confusing

### ISSUE THREAD

**Issue by P1llus** [elastic/ecs#506]
There is a few uncertainties I have with the client part of the field reference, located here: https://github.com/elastic/ecs/blob/1.0/docs/field-details.asciidoc

I will do some more investigations myself to confirm the exact usage of each field, but I was hoping maybe it could be clarified for the next person that is looking it up and might not have a ELK stack available to test on.

The parts I didn't understand is the following:

1. Could example values be included like it is for much of the other references?

2. Already having source and destination, client I guess would be the source in case of for example web logs (apache etc)? Would both the source and the client field be available then? And what would be the difference?

3. When it is mentioned that address can be both IP, domain and unix socket, does this mean the IP/Domain/Socket that the client is connecting to, or the IP/Hostname of the client?

**Comment by anhlqn** [comment]
2. I have the same concern about the client/server and source/destination pairs because I don't know which pair to use for web log and Netflow. It would be less confusing if ECS use only one pair, perhaps source/destination is more generic and matches most use cases.

It would be nice if ECS document provides a mapping from the original fields to ECS fields for the most popular log types like apache, nginx, netflow, Cisco, Juniper, etc.

**Comment by MikePaquette** [comment]
@P1llus thanks for the feedback.

> Could example values be included like it is for much of the other references?

Yes, this is a good suggestion and we should all strive to include examples to assist with understanding and correct usage.

> Already having source and destination, client I guess would be the source in case of for example web logs (apache etc)? Would both the source and the client field be available then? And what would be the difference?

In general, the `source.*` and `destination.*` ECS fields should always be populated for network events or events that contain information about a network transaction.  In addition, if the event contains information that allows the identification of the client and server roles within the network transaction, as defined in ECS [client](https://www.elastic.co/guide/en/ecs/current/ecs-client.html) and [server](https://www.elastic.co/guide/en/ecs/current/ecs-server.html) documentation, then the ECS `client.*` and `server.*` fields should *also* be populated, with the same information, allocated as appropriate.

The client.address field was added to ECS to allow for mapping of the client field in logs such as [Apache HTTP access logs](https://httpd.apache.org/docs/1.3/logs.html) where the client field could contain an IP address, but alternatively could contain a looked-up hostname, for example if Apache [HostnameLookups directive](https://httpd.apache.org/docs/1.3/mod/core.html#hostnamelookups) is enabled. 
In this case the ECS `client.address` field would be populated with whatever value is in the Apache client field, and if it is indeed an IP address, then the ECS `source.ip` and `client.ip` fields would also be populated with the same value.
can add semantic context to an exchange, which is helpful to visualize the data in certain situations. 

> When it is mentioned that address can be both IP, domain and unix socket, does this mean the IP/Domain/Socket that the client is connecting to, or the IP/Hostname of the client?

It refers to the client initiating the transaction.  In the case of [Apache access logs](https://httpd.apache.org/docs/1.3/logs.html) `This is the IP address of the client (remote host) which made the request to the server. If HostnameLookups is set to On, then the server will try to determine the hostname and log it in place of the IP address. However, this configuration is not recommended since it can significantly slow the server. Instead, it is best to use a log post-processor such as logresolve to determine the hostnames. The IP address reported here is not necessarily the address of the machine at which the user is sitting. If a proxy server exists between the user and the server, this address will be the address of the proxy, rather than the originating machine.`

@anhlqn to address your questions:

> I have the same concern about the client/server and source/destination pairs because I don't know which pair to use for web log and Netflow. It would be less confusing if ECS use only one pair, perhaps source/destination is more generic and matches most use cases.

As mentioned above, in general, the `source.*` and `destination.*` ECS fields should always be populated for network events or events that contain information about a network transaction.  In addition, if the event contains information that allows the identification of the client and server roles within the network transaction, as defined in ECS [client](https://www.elastic.co/guide/en/ecs/current/ecs-client.html) and [server](https://www.elastic.co/guide/en/ecs/current/ecs-server.html) documentation, then the ECS `client.*` and `server.*` fields should *also* be populated, with the same information, allocated as appropriate.

> It would be nice if ECS document provides a mapping from the original fields to ECS fields for the most popular log types like apache, nginx, netflow, Cisco, Juniper, etc.

Yes, that's a good idea.  There are a couple logical mapping examples in this repo that might be helpful, [Palo Alto logs](https://github.com/elastic/ecs/issues/352), and [CEF logs](https://github.com/elastic/ecs/issues/433)

**Comment by anhlqn** [comment]
@MikePaquette thanks for clarifying the source/dest and client/server pairs. I guess adding semantic context comes with the cost of additional storage, but at least I now understand how I can continue to analyze web logs and Netflow logs.

**Comment by ebeahan** [comment]
The [Mapping Network Events](https://www.elastic.co/guide/en/ecs/current/ecs-mapping-network-events.html) section exists now in the ECS documentation. The included mapping examples should help ECS users understand the relationships between `source.*`/`destination.*`, `client.*`/`server.*`, and `*.address`/`*.ip`/`*.host`.
