### ISSUE TITLE
Ports formatting incorrectly in template

### ISSUE THREAD

**Issue by andrewthad** [elastic/ecs#686]
In https://github.com/elastic/ecs/pull/454/files, port fields (e.g. `source.port`) were changed to be displayed as strings without commas. However, the Elasticsearch template file that comes with the ECS repo does not set the display format for port fields correctly.

**Comment by webmat** [comment]
@andrewthad The formatting option is actually for Kibana index patterns, which are only generated by Beats at the moment. So this only takes effect in these index patterns.

Would you be interested in having the ECS repo come with an index pattern as well?

**Comment by andrewthad** [comment]
Sorry, I misunderstood how the `format` option is supposed to work. It sounds like Elasticsearch itself has no concept of a display format, which makes sense since all it can do is output JSON. Consequently, the Elasticsearch template could not possibly have this information.

I've just found Kibana's documentation on [Numeric Field Formatters](https://www.elastic.co/guide/en/kibana/current/field-formatters-numeric.html). It would be useful if the ECS repo included some kind of build artifact that make it easy to apply these field formatters to kibana index patterns (either that or creating kibana index patterns with the field formatters). I've never automated the creation of index patterns before since created them in the UI has always been simple and worked well, but being getting out-of-the-box field formatting would definitely tip the scales here.

**Comment by webmat** [comment]
Yeah. We haven't tried shipping a sample index pattern along with the sample Elasticsearch template, so far.

I'm not sure it would work to ship this from the ECS repo, upon further thought. 1) it would be clunky, and 2) it would require some work to make it properly useable.

1) It would be clunky: In order to use an index pattern successfully, it would have to be imported before anyone creates an index pattern for the relevant indices, in Kibana. It's not a big deal to delete and import another index pattern. But it becomes more annoying if the index pattern has already been used to create further Kibana objects (saved searches, visualizations, etc). Beats "gets away" with this because everything (from ES index template, Kibana index pattern, all the way to dashboards) gets imported at the same time during the Beats setup operation.

2) The current ES template is meant for experimentation. As such, its settings and index glob (`ecs-*`) are optimized for experimentation, not for production. For example, the ECS project doesn't mandate anything about the index name. The above is just to simplify experiments. "ecs-experiment1", "ecs-experiment2", etc :-) So shipping a Kibana index pattern would have the same limitations.

But as you've noticed, you can simply adjust your existing index patterns to tweak the formatting of the output to remove the numeric commas. Another interesting one to check out is the string/url rendering :-)

**Comment by ebeahan** [comment]
Once we have `_meta` implemented, Kibana will be able to generate index patterns that match numerics better. See https://github.com/elastic/ecs/issues/721
