### ISSUE TITLE
more geo fields

### ISSUE THREAD

**Issue by enotspe** [elastic/ecs#699]
From a real scenario.

We monitor all APs and switches from a university, which has many campus, each campus has many buildings, each building has many floors, each floor many rooms, a room can be a telecom room with many racks, and on a rack could be many switches.

`geo.name` is not enough for accurate describe the location of a given device (host).

There should be

`geo.site`
`geo.building` 
`geo.floor`
`geo.room`
`geo.rack`
`geo.rack_unit` or `geo.ru`

**Comment by dainperkins** [comment]
@enotspe 
I like the thought - I've also seen this sort of convention in many places from an asset management perspective.  

I'm wondering should this be under geo, or should we consider something under organization to not confuse the general geo fields in use (generally speaking - broad categorization of location based on IP info) with organization specific location and asset management details?

**Comment by enotspe** [comment]
>**Geo Fields Description**
>
> Geo fields can carry data about a specific location related to an event.
> This geolocation information can be derived from techniques such as Geo IP, or be user-supplied.

The new proposed fields enrich geolocation information and are derived from user-supplied sources. So I think they should stay under geo.

**Comment by webmat** [comment]
Yeah I'd tend to agree with @enotspe on this one. These are attributes that are specific to datacenters, but essentially, this is geo information as well. Just finer grained.

For the record, `geo.name` is already meant as a free form / customizable field, and isn't really expected to come from the geoip plugin.

Another point, I initially insisted on calling the field set "geo" rather than "geoip" specifically for that purpose. The "-ip" part was just one of the ways of getting location information.

Location information can be derived in many ways. Geoip, agent static configuration, enrichment based on custom processing. Even a vanilla geoip setup can be supercharged by tampering with the DB (adding private entries or adding columns/attributes).

So overall, I think having more fields under `geo` to cater to datacenter management would totally make sense.

**Comment by ebeahan** [comment]
There are no plans in the mid-term to introduce these finer-grained location details to the `geo.*` field set. For now, the `geo.*` fields will continue focusing on geopositioning details related to a set of geographic coordinates.

[Custom fields](https://www.elastic.co/guide/en/ecs/current/ecs-custom-fields-in-ecs.html) are an option for users interested in collecting more specific location details for their particular use cases.
