### ISSUE TITLE
Inconsistency between related.user and user.* object

### ISSUE THREAD

**Issue by vbohata** [elastic/ecs#779]
Description of "related.user" says "All the user names seen on your event.". In this case the field related.user should be "related.user.name" as "related.user" should be object. I can imagine user.id should be also very useful in related section but it is impossible to add in the future with the related.user set to keyword.

**Comment by janniten** [comment]
@vbohata I agree with you.  @webmat  what do you think?
Regards
Ana

**Comment by ebeahan** [comment]
Like how `related.hosts` is intended for all hostnames or host identifiers seen on an event, `related.user` should include any usernames or user identifies seen on an event. I think the field description for `related.user` could be improved to better capture that intent.

The `related.*` fields are meant to facilitate pivoting with a trivial query. I think by turning the `related.*` fields into more complex objects, some of that simplicity would loss. Instead of simply querying `related.user:alice`, you would have to be more familiar with the object structure. For example, is it `related.user.name` or `related.user.id`?

**Comment by ebeahan** [comment]
Opened #1355 to track improving the `related.user` field's description.

**Comment by janniten** [comment]
Hi @ebeahan 
Today I was just about to post about this topic. I'm working with some windows events (4673,4732) where it would be useful to have the related.user.id in order to pivot data. Sometimes the user name is not present in the event and you need to pivot over the user id to find in a related event the user name. I found that case today while I was analyzing the event 4732 ( add user to a group) with not user name (MemberName) but with user id (MemberSID).

**Comment by janniten** [comment]
I'll prepare some examples in order to show the importance to have the related.user.id field

**Comment by janniten** [comment]
Hi @ebeahan ,
I agree with you that turning a related.user into an object will be go against the simplicity, but I found some cases where would be useful to have in the related.user the full user object
Here an example
Consider the windows event 4732 (A member was added to a security-enabled local group). From the event 4732 documentation: "For local groups this field typically has “-“ value, even if new member is a domain account. For some well-known security principals, such as LOCAL SERVICE or ANONYMOUS LOGON, the value of this field is “-”."
So is not possible to identify which member was added to the group, but...
There is a lot of events where the SID information is present as well as the user.name so if we were able to pivot with the related.user.id the final user could be easily found

![image](https://user-images.githubusercontent.com/33020901/118268737-10963f00-b4be-11eb-9173-b3fa01decbf6.png)

![image](https://user-images.githubusercontent.com/33020901/118268821-2b68b380-b4be-11eb-900d-7cd96d325db1.png)

Is the best way to do it to have in the related.user the entire user object?
What to you think?
Thank you!

**Comment by ebeahan** [comment]
Each `related.*` field is intended to store an array of all seen related values (IP, user, hash, etc.) within an event to their corresponding field. In the case of `related.user`, those values should be any username or user identifier within an event (#1355 has been opened to improve the current description to reflect that intent better).

If only SID is present and added to `related.user` in one event:

`related.user: [ "S-1-5-21" ]`

But the SID plus username are present and added to `related.user` in another:

`related.user [ "S-1-5-21", "pozo" ]`

Querying for `related.user:"S-1-5-21"` will return both events.

As long as the data source was populating `related.user` with all the necessary usernames _and_ user identifiers, the existing `related.user` field would accomplish the need here. WDYT?

**Comment by janniten** [comment]
Hi @ebeahan 
Perfect. Preserve simplicity and allow us to find the user either by username or by id.
I'll create a PR in order to add the SID to the related.user in the winlogbeat security module
Shall I wait for https://github.com/elastic/ecs/issues/1355 to be closed ?
Thank you!

**Comment by ebeahan** [comment]
@janniten I don't believe you need to wait to start work on your PR. I've opened #1420, and we continue the ECS discussion in parallel.

**Comment by ebeahan** [comment]
Improved the `related.user` field description in https://github.com/elastic/ecs/pull/1420
