### ISSUE TITLE
integrate elastic siem signal object into ecs

### ISSUE THREAD

**Issue by willemdh** [elastic/ecs#794]
Hello,

While experimenting with Elastic SIEM External Alert functionality, I noticed the signal object is (not yet) in the ECS template. As I would like to populate some siem related fields such as signal.rule.tactic.name and others, I was wondering if it is planned to integrate the signal object into ecs or not?

Grtz

Willem

**Comment by arledesma** [comment]
Would this be considered [threat](https://github.com/elastic/ecs/blob/master/schemas/threat.yml)?

**Comment by willemdh** [comment]
Signals is about detections of threats?

**Comment by MikePaquette** [comment]
Hi @willemdh, you are correct. The `signal.*` fields used by the Elastic SIEM app are not in the ECS template, nor in the ECS spec. There are no current plans to add them. This is because ingestion pipelines are not expected to populate any `signal.*` fields.  

Signals are Elasticsearch documents created by the SIEM app detection engine when SIEM rule conditions are satisfied.  Only the SIEM app detection engine populates `signal.*` fields.  To help reinforce this, ECS defines a reserved "signal" value of event.kind [here](https://www.elastic.co/guide/en/ecs/current/ecs-allowed-values-event-kind.html#ecs-event-kind-signal).

If you want your events to contain information about threat tactics or techniques, then you can populate, as @arledesma suggests, the `threat.*` [fields](https://www.elastic.co/guide/en/ecs/current/ecs-threat.html) such as `threat.tactic.name` and `threat.technique.name`.

The field you mention, `signal.rule.tactic.name` exists in the SIEM signals indices, and is populated by the SIEM rule's `MITRE ATT&CK™ tactic` setting, which can be selected during the SIEM app Create new rule dialog as shown below.
![image](https://user-images.githubusercontent.com/22619280/77308262-1127b100-6cd1-11ea-9270-fb23b6cd1783.png)

Note that if you create a SIEM detection rule to detect your threat-related events that contain ECS `threat.tactic.name`, and in that SIEM rule, you specify a MITRE ATT&CK™ tactic as shown above, the resultant SIEM signal document would contain _both_ values:  your value would be copied into `signal.threat.tactic.name`, and the rule setting would be in `signal.rule.tactic.name`.

**Comment by willemdh** [comment]
@MikePaquette Thanks for clarifying. I was hoping to add the signal data during ingestion process in a Logstash pipeline. For some use cases, we know it maps to a ttp. Ingesting with this information, only to find it later with elastic siem seemed a bit redundant.

**Comment by webmat** [comment]
If you have good well tuned detections in one type of system, they'll show up as an external alert in SIEM. You can transform all of these into signals with a catch-all for that alert source. You don't need to re-create a 1:1 mapping of these alerts in SIEM, as that indeed would be redundant :-)

**Comment by willemdh** [comment]
Thanks all, closing!
